// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class MatrixWrapper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject matrixWrapperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.MatrixWrapper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SortAlgorithm("SortAlgorithm");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MatrixWrapper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.MatrixWrapper"));
	}

	protected MatrixWrapper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject matrixWrapperMendixObject)
	{
		if (matrixWrapperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.MatrixWrapper", matrixWrapperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.MatrixWrapper");

		this.matrixWrapperMendixObject = matrixWrapperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MatrixWrapper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.MatrixWrapper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.MatrixWrapper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.MatrixWrapper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.MatrixWrapper(context, mendixObject);
	}

	public static myfirstmodule.proxies.MatrixWrapper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.MatrixWrapper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of SortAlgorithm
	 * @param sortalgorithm
	 */
	public final myfirstmodule.proxies.SortAlgorithms getSortAlgorithm()
	{
		return getSortAlgorithm(getContext());
	}

	/**
	 * @param context
	 * @return value of SortAlgorithm
	 */
	public final myfirstmodule.proxies.SortAlgorithms getSortAlgorithm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SortAlgorithm.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.SortAlgorithms.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SortAlgorithm
	 * @param sortalgorithm
	 */
	public final void setSortAlgorithm(myfirstmodule.proxies.SortAlgorithms sortalgorithm)
	{
		setSortAlgorithm(getContext(), sortalgorithm);
	}

	/**
	 * Set value of SortAlgorithm
	 * @param context
	 * @param sortalgorithm
	 */
	public final void setSortAlgorithm(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.SortAlgorithms sortalgorithm)
	{
		if (sortalgorithm != null)
			getMendixObject().setValue(context, MemberNames.SortAlgorithm.toString(), sortalgorithm.toString());
		else
			getMendixObject().setValue(context, MemberNames.SortAlgorithm.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return matrixWrapperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.MatrixWrapper that = (myfirstmodule.proxies.MatrixWrapper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.MatrixWrapper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
